### ISSUE TITLE
Navigating to partial URL shows valid looking results

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#201] opened 2017-11-07 12:40 UTC
Navigating to http://fortis-portal.52.167.224.142.nip.io/#/sites/

shows a site header, not an error or a message that the site doesn't exist. 
Dashboard link brings up an undefined site.

![image](https://user-images.githubusercontent.com/8771377/32494248-80897ea8-c386-11e7-9ed2-444df8f19eae.png)

**Comment by c-w** [comment] 2017-12-05 18:41
This has the same root cause as https://github.com/CatalystCode/project-fortis-pipeline/issues/202. Resolving in favor of https://github.com/CatalystCode/project-fortis-pipeline/issues/202.

**Closed as completed by c-w** 2017-12-05 18:41 UTC
