### ISSUE TITLE
No PowerBI export

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#179] opened 2017-11-07 00:26 UTC
Customers are asking for export to PowerBI to build custom dashboards or to combine fortis data with other data sources.

**Comment by c-w** [comment] 2017-12-05 18:28
@xtophs Could we achieve this today by exporting data from Fortis into CSV and then importing it into PowerBI? We already have a CSV export feature.

**Comment by c-w** [comment] 2017-12-12 17:49
Confirming that PowerBI has CSV import functionality https://docs.microsoft.com/en-us/power-bi/service-get-data#files

**Comment by c-w** [comment] 2018-01-03 18:44
Confirmed that the CSV export works (see attached sample files) and resolving since data can be ingested into PowerBI via CSV.

[timeSeries.csv.txt](https://github.com/CatalystCode/project-fortis-pipeline/files/1601371/timeSeries.csv.txt)
[popularLocations.csv.txt](https://github.com/CatalystCode/project-fortis-pipeline/files/1601372/popularLocations.csv.txt)
[topTerms.csv.txt](https://github.com/CatalystCode/project-fortis-pipeline/files/1601373/topTerms.csv.txt)

For programmatic access, the GraphQL API can be used to access/export the data.

Please re-open the issue if you feel strongly about this feature -- adding a direct line to PowerBI will be a non-trivial feature to implement. If the PowerBI features is implemented, the question must be raised why we don't just implement the entire Fortis UI in terms of PowerBI widgets instead of maintaining the React frontend, but we simply don't have resources for this work.

**Closed as completed by c-w** 2018-01-03 18:44 UTC
Labels: Low Priority Task, frontend
