### ISSUE TITLE
Inconsistent UI

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#218] opened 2017-11-08 12:59 UTC
* bring up site: http://fortis-portal.52.167.224.142.nip.io/#/site/armedconflict
* change filter to rafaga (gunfire)
* all Widgets update, including wordcloud showing different terms

word cloud does not include new filter term (rafaga). Might be by design, but it's confusing

![image](https://user-images.githubusercontent.com/8771377/32550235-511d4062-c45a-11e7-8308-712cdaee21cf.png)

![image](https://user-images.githubusercontent.com/8771377/32550302-950f17be-c45a-11e7-8b1f-4ba200535c8e.png)

**Comment by c-w** [comment] 2017-12-05 18:12
Pretty sure that this is by design and the popular-topics chart is supposed to show the globally top mentioned words.

The data-source that feeds this graph is defined in CQL like so: https://github.com/CatalystCode/project-fortis-pipeline/blob/aa05b05bc84b79f6a3c6a308c8f8a87380edc4c9/ops/storage-ddls/cassandra-setup.cql#L248-L264

As you can see in the CQL definition, we only track the counts of words by pipeline (e.g. Facebook), source (e.g. AlJazeera) and geographical bounding box. As such, we couldn't update the word-cloud when a topic gets selected, e.g. to show the most popular words associated with the word. We just don't have the data for this currently.

We could enable this feature, but it would require:

- Changing the data model in Cassandra to add a new view
- Adding a new query in the GraphQL server to vend the new data
- Updating the interface to make use of the new query

I'd estimate this to be at least 1-2 developer-weeks of effort.

Given this new information, would you still like to prioritize this @xtophs and @dmakogon? If not, we should think about alternative ways to make the UI more intuitive, e.g. grey-out the top-sources chart once a topic is selected. Thoughts?

**Comment by c-w** [comment] 2018-01-02 15:18
Resolving as by-design as per earlier discussion. Please re-open if you still feel strongly about this in the light of the extra information above.

**Closed as completed by c-w** 2018-01-02 15:18 UTC
Labels: Critical Task, frontend
