### ISSUE TITLE
Setup only allows a single geofence to filter events

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#181] opened 2017-11-07 00:36 UTC
Customers may want finer grained configuration options, beyond a single rectangle to define the desired origin of events.  Combined with lack of cloning a site, configuring a site for non-contiguous geographies is too hard.

**Comment by erikschlegel** [comment] 2017-11-28 04:21
The geofence tab in the admin module should support allowing users to define multiple geofences.

**Comment by c-w** [comment] 2017-12-05 15:35
A lot of Fortis is designed with a single geo-fence in mind. As a matter of fact, the architecture also assumes that the geo-fence is rarely (if ever) changing and if I remember design discussions around the April/May timeframe correctly, this was a conscious decision. Changing this now and allowing multiple geo-fences would be a deep-cutting and expensive change. I'd estimate at least 2-3 developer weeks. Given this additional information, is this still something that we want to invest into, @xtophs or @dmakogon?

**Comment by c-w** [comment] 2017-12-12 14:09
Had a chat with @xtophs the other day. One of the main reasons for the ask in #178 was the desire to monitor multiple geo-fences, so if we implement #178, we'd be able to monitor multiple geo-fences by setting up site clones, so resolving as a duplicate of #178.

**Closed as completed** 2017-12-12 14:10 UTC
