### ISSUE TITLE
Blue sentiment color in item feed

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#203] opened 2017-11-07 12:54 UTC
Blue doesn't seem to be used as sentiment color anywhere else:

![image](https://user-images.githubusercontent.com/8771377/32494736-6d9bba02-c388-11e7-94ca-9d277e9bf9d7.png)

**Comment by c-w** [comment] 2017-12-05 18:38
This has the same root cause as https://github.com/CatalystCode/project-fortis-pipeline/issues/191. Resolving this issue in favor of https://github.com/CatalystCode/project-fortis-pipeline/issues/191.

**Closed as completed by c-w** 2017-12-05 18:38 UTC
