### ISSUE TITLE
Top Terms inconsistent

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#212] opened 2017-11-08 12:37 UTC
* Open site http://fortis-portal.52.167.224.142.nip.io/#/site/armedconflict
* select Last Week

Word Cloud shows muert as #2 most popular term with 495 mentions. muert does not show in the Top 5 terms, even though it has more mentions than the displayed term capturado with 113 mentions.

![image](https://user-images.githubusercontent.com/8771377/32549412-5a34a1f2-c457-11e7-8386-d03d4b6c296e.png)

**Comment by erikschlegel** [comment] 2017-11-28 03:46
The top 5 in this list represents conjunctive filters, so in the case mentioned above policia + capturado was mentioned in 113 tweets, policia + captura mentioned 110 instances, etc. Muert was mentioned a total of 495 instances, but you wouldn't see that in the filters section as you selected policia as your main term. The issue is more of a user experience issue where we need to be more clear with the labels of the Filters section.

**Comment by c-w** [comment] 2018-01-02 15:02
Resolving as duplicate of https://github.com/CatalystCode/project-fortis-pipeline/issues/192 since the "top terms" is now removed.

**Closed as completed by c-w** 2018-01-02 15:02 UTC
Labels: Critical Task, frontend
