### ISSUE TITLE
Populate a default list of streams into cassandra on site creation

### ISSUE THREAD

**Issue by Smarker** [CatalystCode/fortisdeploy#246] opened 2017-12-07 20:52 UTC
Currently, the user has no way of adding streams to the streams table from the admin page, since the user should only be able to `enable`/`disable` streams or edit stream `parameters`. 

In addition, for each stream, we should add parameter names needed to connect to that stream. For example, for twitter we should add parameters like `consumer_key` and `consumer_secret`, so that it is more clear to the user that he/she would need to enter in those parameter values to connect to twitter.

**Comment by c-w** [comment] 2017-12-08 14:39
Why shouldn't the admin be able to add streams? Adding default streams (which can later be edited) means we'll miss many use-cases such as for example deployments that will want to use many Twitter streams.

**Comment by c-w** [comment] 2017-12-08 15:35
Related to https://github.com/CatalystCode/project-fortis-pipeline/issues/207

**Comment by c-w** [comment] 2017-12-11 16:46
Via @erikschlegel 

> one pipeline type can have many streams, if I'm not mistaken(ie twitter connections)
> I would check to see how it's setup for colombia and use that as your baseline
> So the way it's intended to operate is the following 
> 1) all the available pipelines a user can choose from is defined in a JSON file. Pipelines being Twitter, RSS, Facebook, etc.
> 2) that list of pipelines drive the list options in the streams tab. In this list the user chooses which pipeline(s) should be enabled for their fortis site. The enabled /disabled radio button is driven off the enabled field in streams
> 3) the results of each selection is written to the streams table
> 4) twitter is a special case as you can have multiple stream records as twitter connections are pooled to accommodate the number of keywords we're tracking 
> 5) Connection details for each stream is written to streams.params frozen<map<text, text>>,
> the underlying sources for each stream resides in the trustedsources table
> So the RSS pages, Twitter profiles, Facebook pages, etc

**Comment by c-w** [comment] 2018-01-11 16:55
Closing this as it's a sub-set/duplicate of #207.

**Closed as completed by c-w** 2018-01-11 16:55 UTC
Labels: High Priority Task, devops
