### ISSUE TITLE
Can't reset UI after changing timeline filter

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#183] opened 2017-11-07 00:42 UTC
Repro steps:

navigate to site.
change timeline filter to narrow down time filter

Clicking on Reset does not restore timeline to setting selected by the dropdown in the upper right corner.

Suggestion:
* Remove Reset Button, 
* Rename to reflect what it does
* Move interval dropdown and timeline widget closer together since the former controls scope of the latter.

**Comment by c-w** [comment] 2018-01-02 21:10
Resolving as duplicate of https://github.com/CatalystCode/project-fortis-pipeline/issues/221

**Closed as completed by c-w** 2018-01-02 21:10 UTC
Labels: High Priority Task, frontend
