### ISSUE TITLE
UI doesn't load, bowser stuck at loading armedconfilict watcher...

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#174] opened 2017-11-07 00:14 UTC
Opening 

http://fortis-portal.52.167.224.142.nip.io/#/site/armedconfilict

page stuck at: 

loading armedconfilict watcher...

UI never comes up. Intermittent, but reproduces fairly reliably, almost half the time in Edge and Chrome. Happened on hotel wifi in NYC and Istanbul. F12 shows the UI loaded
![fortis-not-loading](https://user-images.githubusercontent.com/8771377/32470568-4eefa286-c31e-11e7-861e-9b7c81fdf997.png)

**Comment by xtophs** [comment] 2017-11-07 00:15
There doesn't appear to be debug mode to get client side debug output. If there is, it needs to be documented.

**Comment by erikschlegel** [comment] 2017-11-28 04:27
@c-w is this still an issue?

**Comment by c-w** [comment] 2017-11-28 13:45
@erikschlegel We haven't done any testing of the site with low speed connections yet so I have no reason to believe that this is fixed.

**Comment by c-w** [comment] 2018-01-03 20:17
The application bundle is quite large which leads to the page loading slowly on bad networks.

![image](https://user-images.githubusercontent.com/1086421/34537974-7b474efe-f098-11e7-90f7-0112a208e01b.png)

However, even with the "slow 3G" preset in the Chrome network tab, I still manage to load the site eventually:

![image](https://user-images.githubusercontent.com/1086421/34538046-bf90402a-f098-11e7-8d8e-07add215507a.png)

I suspect that the original report was a bug hidden by the fact that we weren't displaying errors during load. We've since rectified that omission and added a loading process indicator. Resolving this; please feel free to re-open if you still manage to reproduce this error.

**Closed as completed by c-w** 2018-01-03 20:17 UTC
Labels: Low Priority Task, frontend
