### ISSUE TITLE
Verify item count and data quality

### ISSUE THREAD

**Issue by xtophs** [CatalystCode/fortisdeploy#194] opened 2017-11-07 12:13 UTC
Bubbles on the map appear to display the count of items in a location. I believe, when you select a bubble, it shows the associated feed it's supposed to show the feed items of that bubble.

Sometimes it shows more items. See screenshot where the bubble has a count of 1, but 4 items are displayed: https://epicstuff.slack.com/files/U4VLP4QBS/F7T3VGMRR/image.png

**Comment by c-w** [comment] 2017-12-12 16:43
Time-boxed investigation to reproduce this and verify data quality: 3 days.

**Comment by Smarker** [comment] 2018-01-22 19:13
Looking at Twitter stream, verify for 100-200 data-points:
- [ ] does what comes out of the streams get into the database
- [ ] does what's in the database show up in the interface

**Comment by Smarker** [comment] 2018-01-22 22:15
Found and fixed bugs:
* **can't save a topic without translations** - fixed (broke when we removed the translations column in sitesettings - fixed by adding the english topic translation as the default translation)
* **after editing the geofence in sitesettings, the map cannot update** - fixed by checking if bbox was string and if so then splitting it by comma to get the bounding box as an array

**Comment by c-w** [comment] 2018-01-24 19:47
Verified that I can reproduce this problem easily. After running a very simple site setup with a single twitter stream and 3 watchlist terms for a few minutes (see [seed-data-twitter.tar.gz](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-pipeline/ops/storage-ddls/seed-data-twitter.tar.gz)) I get the following:

![image](https://user-images.githubusercontent.com/1086421/35353290-b7d6bc38-0114-11e8-9e91-bee4486dce4e.png)
![image](https://user-images.githubusercontent.com/1086421/35353313-cdc9ed30-0114-11e8-8eb8-a7473e34f95e.png)
![image](https://user-images.githubusercontent.com/1086421/35354012-e3c2876c-0116-11e8-853d-d85412f1b24a.png)

There are >1k entries in the various aggregation tables and just 2 entries in the events table. We shouldn't have 4 items shown on the map or 4 mentions counted in the popular sources and timeline. Looks like we're double-counting somewhere.

**Comment by c-w** [comment] 2018-01-24 22:34
Did a bit more digging -- pretty sure the data issues are introduced at the spark layer.

There is quite a bit of complexity in [HeatmapOfflineAggregator](https://github.com/CatalystCode/project-fortis/blob/master/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/aggregators/HeatmapOfflineAggregator.scala#L12) to deal with the fact that the [computedtiles table](https://github.com/CatalystCode/project-fortis/blob/782830e143eda0fbcba57bba775779231990f86a/project-fortis-pipeline/ops/storage-ddls/cassandra-setup.cql#L142-L155) is not a counter table. There is also some complexity in the dedupe logic in [CassandraEventsSink](https://github.com/CatalystCode/project-fortis/blob/db79054ee8ae09e477e504e413c4aad2a8cd2151/project-fortis-spark/src/main/scala/com/microsoft/partnercatalyst/fortis/spark/sinks/cassandra/CassandraEventsSink.scala).

I wonder whether refactoring the Cassandra schema to (a) turn computedtiles into a counter table and (b) turn all the materialized views into counter tables would make the code simpler since then Spark just needs to insert items into the appropriate tables and all the aggregates get computed automatically by Cassandra on the database level.

**Comment by c-w** [comment] 2018-01-26 17:32
Some comments from @jennifermarsman

> https://msdn.microsoft.com/en-us/library/azure/dn835019.aspx 
> so the links at the bottom of this page illustrate the different types of windowing - i'm wondering if SPARK is using a different windowing scheme than you want
> (even though that doc is for stream analytics, not spark)
> tumbling vs. hopping vs sliding windows - based on that, could be pulling in duplicate data.  (that was my first instinct on what might be going wrong)

**Comment by kevinhartman** [comment] 2018-01-31 21:07
Today, the aggregations are run on only the events that were not already in the events table.
Consider the following, where events are represented as integers:
```
batchB = { 1, 2, 3, 4 }
eventTable = { 1, 3, 5 }

aggregationCandidates = batchB - eventTable = { 2, 4 }
```

There are flaws, however. Namely, these computations cannot be done transactionally, so failures can cause data inconsistencies between tables.

Without handling aggregations in Cassandra itself, this was the best we could do given the current schema (though I'm surprised to see that these inconsistencies are so frequent, perhaps indicating a bug).

I can explore the possibility of a schema change, but Cassandra has serious limitations around counter tables and transactional updates, so even replacing materialized views with real counter tables may not get us far enough (you cannot update counter tables within a transaction).

**Comment by c-w** [comment] 2018-02-01 14:42
I didn't seen any errors in the Spark logs, so I doubt that the re-counts are caused by lack of transactions.

**Comment by c-w** [comment] 2018-02-06 18:19
Another example, with a custom location selected (more items shown in news feed vs on the map -- may be a potential issue with the news feed query not respecting the location though, not necessarily general data storage issue):

![image](https://user-images.githubusercontent.com/1086421/35876417-34ab2476-0b40-11e8-89f4-f49351986510.png)

**Comment by c-w** [comment] 2018-02-06 22:45
I thought I had another repro:

![dashboard](https://user-images.githubusercontent.com/1086421/35888402-7ce2f848-0b65-11e8-901a-91fc21898095.PNG)

However, in this case it's just a labelling bug: one event occurs in two places:

![event1](https://user-images.githubusercontent.com/1086421/35888371-69db92aa-0b65-11e8-81c5-3298853bbf84.PNG)

![event2](https://user-images.githubusercontent.com/1086421/35888372-69ea4a7a-0b65-11e8-8d89-e8dcc81d32dc.PNG)

We can fix this confusion by adding pills to the events in the activity feed that display the locations in addition to the keywords.

**Comment by c-w** [comment] 2018-02-20 16:04
This is a really neat tool: https://www.ecyrd.com/cassandracalculator/

![image](https://user-images.githubusercontent.com/1086421/36434753-ca240bba-162d-11e8-80b9-17f5714a011d.png)

**Comment by c-w** [comment] 2018-02-23 13:52
Pull request: https://github.com/CatalystCode/project-fortis/pull/31

**Closed as completed** 2018-02-26 15:15 UTC
Labels: Critical Task, ingestion
